# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'somei' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for someiw
  pod 'Firebase/Firestore'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'

  target 'someiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'someiUITests' do
    # Pods for testing
  end

end
