# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Somei' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Somei
  pod 'Firebase/Firestore'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  
  pod 'FirebaseUI/Auth'
  #pod 'FirebaseUI/Google'
  #pod 'FirebaseUI/Facebook'
  #pod 'FirebaseUI/Twitter'
  #pod 'FirebaseUI/Phone'
  

end
